version: "3"
services:
  limosa:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
      args:
        USER: $USER
        UID: $USER_ID
        DEPLOYMENT_MODE: "prod"
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - limosaGenerated:/var/www/html/storage/limosas
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot:rw,z
    user: "${UID}"
    depends_on:
      - selenium-hub
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      hub:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  firefox:
    image: selenium/node-firefox:4.13.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - limosaGenerated:/home/seluser/Downloads:rw,z
    networks:
      hub:
  selenium-hub:
    image: selenium/hub:4.13.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      hub:
  redis:
    image: redis:latest
    depends_on:
      - limosa
    networks:
      hub:
  mysql:
    image: mysql:8
    ports:
      - 3307:3307
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: limosa
    depends_on:
      - limosa
    networks:
      hub:
    volumes:
        - dbData:/var/lib/mysql
volumes:
  limosaGenerated: {}
  dbData: {}
networks:
  hub:
    driver: bridge
